"""
NX-OS Exporter - Exports generated configs as per-device .cfg files in a ZIP archive.
"""
import io
import zipfile
from typing import Any

from .fabric_model import FabricModel
from .config_engine import ConfigEngine


class NxosExporter:
    """Exports per-device NX-OS config files as a ZIP archive."""

    def __init__(self, model: FabricModel):
        self.model = model
        self.engine = ConfigEngine(model)

    def export(self) -> bytes:
        """Generate all configs and package into a ZIP. Returns ZIP bytes."""
        configs = self.engine.generate_all()

        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            for hostname, config_text in sorted(configs.items()):
                filename = f"{hostname}.cfg"
                zf.writestr(filename, config_text)

            manifest = self._build_manifest(configs)
            zf.writestr("_manifest.txt", manifest)

        zip_buffer.seek(0)
        return zip_buffer.getvalue()

    def export_single(self, device_id: str) -> str:
        """Export config for a single device."""
        return self.engine.get_device_config(device_id)

    def _build_manifest(self, configs: dict[str, str]) -> str:
        lines = [
            "# VXLAN Fabric Configuration Package",
            f"# Generated by Classic Fabric Visualiser - Fabric Builder",
            f"# Total Devices: {len(configs)}",
            "",
            "Files:",
        ]
        for hostname in sorted(configs.keys()):
            device = self.model.get_device(hostname)
            role = device.role if device else "unknown"
            lines.append(f"  {hostname}.cfg  ({role})")
        return "\n".join(lines)
